### PR TITLE
UserData Models & Provider

### PR DESCRIPTION
**Pull request by SimonTod**

### CODE REVIEW

**Comment by victorino-s** [comment]
- IUserDataProvider.findUser(User user) should be findUser(int id) OR / AND findUser(string userId).
(as you only use the userId to build your query, you don't have to use a User object in params)

- Remove unused comments (UserDataProvider.java line 79).

What's the purpose of Rest.java ?

**Review by ThomasDro — APPROVED** [review]

**Comment by SimonTod** [comment]
Once the branch will be merged with master, I will change my class to use the options file for the UserData Web Service base url.

**Review by methiev — APPROVED** [review]
Still need to implement the configuration of all the hard coded values

**Review by victorino-s — APPROVED** [review]
Note : Do not forget to put connection strings in a config file.

**Comment by SimonTod** [comment]
[Provider UserData](https://trello.com/c/S5pX4RiP/54-provider-userdata)

**Pull request merged**
