### PR TITLE
merge MobileWebService to master

### PR DESCRIPTION
**Pull request by SimonTod**

### CODE REVIEW

**Review by methiev — APPROVED** [review]
I'm fine with these changes

**Comment by SimonTod** [comment]
[2.1. [Mobile API] Check user identity / 4h](https://trello.com/c/nNFcfYG6/5-21-mobile-api-check-user-identity-4h)

**Comment by SimonTod** [comment]
[2.2. [Mobile API] Retrieve all devices for a user](https://trello.com/c/cKhnj1E2/6-22-mobile-api-retrieve-all-devices-for-a-user)

**Comment by SimonTod** [comment]
[2.2. [Mobile API] Retrieve all devices for a user](https://trello.com/c/cKhnj1E2/6-22-mobile-api-retrieve-all-devices-for-a-user)

**Comment by SimonTod** [comment]
[2.1. [Mobile API] Check user identity / 4h](https://trello.com/c/nNFcfYG6/5-21-mobile-api-check-user-identity-4h)

**Comment by SimonTod** [comment]
[2.3. [Mobile API] Retrieve the latest metrics for a specific device](https://trello.com/c/qD52D7Ro/7-23-mobile-api-retrieve-the-latest-metrics-for-a-specific-device)

**Comment by SimonTod** [comment]
[2.4. [Mobile API] Retrieve metrics calculated by the calc engine](https://trello.com/c/F7CUomMp/8-24-mobile-api-retrieve-metrics-calculated-by-the-calc-engine)

**Pull request merged**
